// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://forensant.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://forensant.com/support",
            "email": "support@forensant.com"
        },
        "license": {
            "name": "Commercial",
            "url": "https://proximity.forensant.com/terms"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/inject_operation": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates the properties of an inject operation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Injection Operations"
                ],
                "summary": "Update Inject Operation",
                "parameters": [
                    {
                        "description": "Injection details in JSON format (not all fields can be set)",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.InjectOperation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inject_operation/archive": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates the the archived status of an inject operation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Injection Operations"
                ],
                "summary": "Archive Inject Operation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "inject operation guid",
                        "name": "guid",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "archive status to set",
                        "name": "archive",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inject_operation/run": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "creates and runs an injection operation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Injection Operations"
                ],
                "summary": "Run an Injection Operation",
                "parameters": [
                    {
                        "description": "Injection details in JSON format (not all fields can be set)",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.InjectOperation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inject_operations": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a list of all injection operations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Injection Operations"
                ],
                "summary": "Get All Inject Operations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.InjectOperation"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inject_operations/payloads": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets all available payloads available for injection",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Injection Operations"
                ],
                "summary": "Gets injection payloads",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.PayloadEntry"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/project/request": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a specific request",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Get A Request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The GUID of the request to fetch",
                        "name": "guid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/project.RequestSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates a specific request",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Update A Request",
                "parameters": [
                    {
                        "description": "The GUID of the request to update",
                        "name": "guid",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "The notes for the request",
                        "name": "notes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/project/requestresponse": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets the full request and response of a given request",
                "produces": [
                    "text/text"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Get Request and Response",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/project/requests": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a list of all requests",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Get All Requests",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scan ID",
                        "name": "scanid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Only show requests which contain the filter string in the url, request, response, etc",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Only show requests which contain the given string in the URL",
                        "name": "url_filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Column to sort by (default time)",
                        "name": "sort_col",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Column direction to sort by (default asc)",
                        "name": "sort_dir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.Request"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/project/script": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a single script",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Get A Script",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/project/script/append_html_output": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "appends the given HTML to the HTML output of the script",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Append HTML Output for a Script",
                "parameters": [
                    {
                        "description": "HTML Output",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.AppendHTMLScriptParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/project/script/archive": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates the the archived status of a script",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Archive Script",
                "parameters": [
                    {
                        "type": "string",
                        "description": "script guid",
                        "name": "guid",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "archive status to set",
                        "name": "archive",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/project/scripts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a list of all scripts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Get All Scripts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.ScriptRun"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/project/sitemap": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a list of all paths observed by the proxy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Gets the sitemap",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/proxy/add_request_to_queue": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "add a request to the queue for scanning sites",
                "tags": [
                    "Requests"
                ],
                "summary": "Add Request to Queue",
                "parameters": [
                    {
                        "description": "Request Details",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.AddRequestToQueueParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/proxy/ca_certificate.pem": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "returns the certificate authority root certificate",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "Gets the root CA",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/proxy/intercept_settings": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get intercept settings",
                "tags": [
                    "Settings"
                ],
                "summary": "Get Intercept Settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.InterceptSettings"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "set intercept settings",
                "tags": [
                    "Settings"
                ],
                "summary": "Set Intercept Settings",
                "parameters": [
                    {
                        "description": "Proxy Intercept Settings Object",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.InterceptSettings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/proxy/intercepted_requests": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a list of all requests which have been intercepted, which are awaiting a response",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Get Intercept Requests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.InterceptedRequest"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/proxy/make_request": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "makes a single request to a given server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Make a single request",
                "parameters": [
                    {
                        "description": "Make Request Parameters in JSON format",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.MakeRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/proxy/set_intercepted_response": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "set how an intercepted request will be responded to",
                "tags": [
                    "Settings"
                ],
                "summary": "Modify Intercepted Request",
                "parameters": [
                    {
                        "description": "Proxy Intercept Response Object",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.InterceptedRequestResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/proxy/settings": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get proxy settings",
                "tags": [
                    "Settings"
                ],
                "summary": "Get Proxy Settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.ProxySettings"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "set proxy settings",
                "tags": [
                    "Settings"
                ],
                "summary": "Set Proxy Settings",
                "parameters": [
                    {
                        "description": "Proxy Settings Object",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.ProxySettings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scripts/cancel": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "cancels the provided script",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Cancel the running script",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Script to cancel",
                        "name": "guid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scripts/run": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "runs the provided script",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Run provided script",
                "parameters": [
                    {
                        "description": "Run Script Parameters in JSON format",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scripting.RunScriptParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scripts/update_progress": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates the progress of a currently running script",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Updates running script progress",
                "parameters": [
                    {
                        "description": "Update Details",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.ScriptProgressUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "project.AppendHTMLScriptParameters": {
            "type": "object",
            "properties": {
                "guid": {
                    "type": "string"
                },
                "outputHTML": {
                    "type": "string"
                }
            }
        },
        "project.InjectOperation": {
            "type": "object",
            "properties": {
                "archived": {
                    "type": "boolean"
                },
                "customFilenames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "customPayloads": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "doNotRecord": {
                    "type": "boolean"
                },
                "error": {
                    "type": "string"
                },
                "fuzzDB": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "guid": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "injectDescription": {
                    "type": "string"
                },
                "iterateFrom": {
                    "type": "integer"
                },
                "iterateTo": {
                    "type": "integer"
                },
                "objectType": {
                    "type": "string"
                },
                "percentCompleted": {
                    "description": "Parts of the object which cannot be set by JSON",
                    "type": "integer"
                },
                "request": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/project.InjectOperationRequestPart"
                    }
                },
                "requestsMadeCount": {
                    "type": "integer"
                },
                "ssl": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "totalRequestCount": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "project.InjectOperationRequestPart": {
            "type": "object",
            "properties": {
                "inject": {
                    "type": "boolean"
                },
                "requestPart": {
                    "type": "string"
                }
            }
        },
        "project.InterceptedRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "\u003cbase64 encoded body\u003e"
                },
                "direction": {
                    "type": "string",
                    "example": "Either browser_to_server or server_to_browser"
                },
                "objectType": {
                    "type": "string"
                },
                "recordAction": {
                    "type": "string",
                    "example": "Either add or delete"
                },
                "request": {
                    "$ref": "#/definitions/project.Request"
                }
            }
        },
        "project.Request": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "guid": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "objectType": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "responseContentType": {
                    "type": "string"
                },
                "responseSize": {
                    "type": "integer"
                },
                "responseStatusCode": {
                    "type": "integer"
                },
                "responseTime": {
                    "type": "integer"
                },
                "scanID": {
                    "type": "string"
                },
                "time": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "verb": {
                    "type": "string"
                }
            }
        },
        "project.RequestSummary": {
            "type": "object",
            "properties": {
                "guid": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "requestData": {
                    "type": "string"
                }
            }
        },
        "project.ScriptProgressUpdate": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "guid": {
                    "type": "string"
                },
                "objectType": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "project.ScriptRun": {
            "type": "object",
            "properties": {
                "development": {
                    "type": "boolean"
                },
                "doNotRecord": {
                    "type": "boolean"
                },
                "error": {
                    "type": "string"
                },
                "guid": {
                    "type": "string"
                },
                "htmlOutput": {
                    "type": "string"
                },
                "objectType": {
                    "type": "string"
                },
                "percentCompleted": {
                    "type": "integer"
                },
                "requestsMadeCount": {
                    "type": "integer"
                },
                "script": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "textOutput": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "totalRequestCount": {
                    "type": "integer"
                }
            }
        },
        "proxy.AddRequestToQueueParameters": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "request": {
                    "type": "string",
                    "example": "\u003cbase64 encoded request\u003e"
                },
                "scan_id": {
                    "type": "string"
                },
                "ssl": {
                    "type": "boolean"
                }
            }
        },
        "proxy.InterceptSettings": {
            "type": "object",
            "properties": {
                "browserToServer": {
                    "type": "boolean"
                },
                "serverToBrowser": {
                    "type": "boolean"
                }
            }
        },
        "proxy.InterceptedRequestResponse": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "\u003cbase64 encoded body\u003e"
                },
                "direction": {
                    "type": "string",
                    "example": "Either browser_to_server or server_to_browser"
                },
                "guid": {
                    "type": "string"
                },
                "requestAction": {
                    "type": "string",
                    "example": "One of: forward, forward_and_intercept_response or drop"
                }
            }
        },
        "proxy.MakeRequestParameters": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "request": {
                    "type": "string",
                    "example": "\u003cbase64 encoded request\u003e"
                },
                "scan_id": {
                    "type": "string"
                },
                "ssl": {
                    "type": "boolean"
                }
            }
        },
        "proxy.PayloadEntry": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "isDirectory": {
                    "type": "boolean"
                },
                "resourcePath": {
                    "type": "string"
                },
                "samplePayloads": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subEntries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/proxy.PayloadEntry"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "proxy.ProxySettings": {
            "type": "object",
            "properties": {
                "http11ProxyAddr": {
                    "type": "string"
                },
                "http11UpstreamProxyAddr": {
                    "type": "string"
                },
                "maxConnectionsPerHost": {
                    "type": "integer"
                }
            }
        },
        "scripting.RunScriptParameters": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scripting.ScriptCode"
                    }
                },
                "development": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "scripting.ScriptCode": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "mainScript": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Proximity Core",
	Description: "This provides the common functions which are relied upon by the Proximity frontends.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
