// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package api

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://forensant.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://forensant.com/support",
            "email": "support@forensant.com"
        },
        "license": {
            "name": "Commercial",
            "url": "https://proximity.forensant.com/terms"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/inject_operation/run": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "creates and runs an injection operation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Injection Operations"
                ],
                "summary": "Run an Injection Operation",
                "parameters": [
                    {
                        "description": "Injection details in JSON format (not all fields can be set)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.InjectOperation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inject_operations": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a list of all injection operations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Injection Operations"
                ],
                "summary": "Get All Inject Operations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.InjectOperation"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inject_operations/fuzzdb_payload": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a specific fuzzdb file",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Injection Operations"
                ],
                "summary": "Get a fuzzdb file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The file path of the fuzzdb file to fetch the payload for",
                        "name": "file",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inject_operations/payloads": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets all available payloads available for injection",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Injection Operations"
                ],
                "summary": "Gets injection payloads",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.PayloadEntry"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inject_operations/{guid}/archive": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates the the archived status of an inject operation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Injection Operations"
                ],
                "summary": "Archive Inject Operation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "inject operation guid",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "archive status to set",
                        "name": "archive",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inject_operations/{guid}/title": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates the title of an inject operation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Injection Operations"
                ],
                "summary": "Set Inject Operation Title",
                "parameters": [
                    {
                        "type": "string",
                        "description": "inject operation guid",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "title to set",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inject_operations/{path}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a single inject operation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Injection Operations"
                ],
                "summary": "Get Inject Operation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The GUID of the request to fetch",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/project.InjectOperation"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/notifications": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "websocket endpoint to stream data as it is inserted/modified",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Misc"
                ],
                "summary": "Stream updates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JSON object (key:value) where the returned objects will be filtered by the values",
                        "name": "objectfieldfilter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "additional filter to apply to the objects (behaviour is object dependent)",
                        "name": "filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/out_of_band/url": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a unique URL which can be used to test out of band interactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Out of Band"
                ],
                "summary": "Get Out of Band URL",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "returns a simple request to indicate that the service is up",
                "tags": [
                    "Misc"
                ],
                "summary": "Healthcheck",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/proxy/ca_certificate.pem": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "returns the certificate authority root certificate",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Proxy"
                ],
                "summary": "Gets the root CA",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/proxy/intercept_settings": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get intercept settings",
                "tags": [
                    "Settings"
                ],
                "summary": "Get Intercept Settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.InterceptSettings"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "set intercept settings",
                "tags": [
                    "Settings"
                ],
                "summary": "Set Intercept Settings",
                "parameters": [
                    {
                        "description": "Proxy Intercept Settings Object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.InterceptSettings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/proxy/intercepted_requests": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a list of all requests which have been intercepted, which are awaiting a response",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proxy"
                ],
                "summary": "Get Intercept Requests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.InterceptedRequest"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/proxy/set_intercepted_response": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "set how an intercepted request will be responded to",
                "tags": [
                    "Proxy"
                ],
                "summary": "Modify Intercepted Request",
                "parameters": [
                    {
                        "description": "Proxy Intercept Response Object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.InterceptedRequestResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/proxy/settings": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get proxy settings",
                "tags": [
                    "Settings"
                ],
                "summary": "Get Proxy Settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxy.ProxySettings"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "set proxy settings",
                "tags": [
                    "Settings"
                ],
                "summary": "Set Proxy Settings",
                "parameters": [
                    {
                        "description": "Proxy Settings Object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.ProxySettings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/requests": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a list of all requests",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Get All Requests",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scan ID, can be multiple separated by semi-colons",
                        "name": "scanid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Only show requests which contain the filter string in the url, request, response, etc",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Only show requests which contain the given string in the URL",
                        "name": "url_filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by specific verbs",
                        "name": "verb",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Column to sort by (default time)",
                        "name": "sort_col",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Column direction to sort by (default asc)",
                        "name": "sort_dir",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit to the last n requests (sorted by time)",
                        "name": "last",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.Request"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/requests/make": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "makes a single request to a given server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Make a single request",
                "parameters": [
                    {
                        "description": "Make Request Parameters in JSON format",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.MakeRequestParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/requests/queue": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "add a request to the queue for scanning sites",
                "tags": [
                    "Requests"
                ],
                "summary": "Add Request to Queue",
                "parameters": [
                    {
                        "description": "Request Details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxy.AddRequestToQueueParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/requests/sitemap": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a list of all paths observed by the proxy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Gets the sitemap",
                "parameters": [
                    {
                        "type": "string",
                        "description": "An optional filter on the query to restrict to specific paths",
                        "name": "parent",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "An optional filter on the query to restrict to the paths to those seen for a particular scan",
                        "name": "scan_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/requests/{base_guid}/compare/{compare_guid}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "compares two requests and returns the differences",
                "produces": [
                    "text/text"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Compare Two Requests",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base Request guid",
                        "name": "base_guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request to Compare guid",
                        "name": "compare_guid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.RequestDifference"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/requests/{guid}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a specific request",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Get A Request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The GUID of the request to fetch",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/project.RequestSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/requests/{guid}/contents": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets the full request and response of a given request",
                "produces": [
                    "text/text"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Get Request and Response",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request GUID",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/project.RequestResponseContents"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/requests/{guid}/notes": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates a specific request's notes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Update Request Notes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The GUID of the request to update",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "The notes for the request",
                        "name": "notes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/requests/{guid}/partial_data": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets part of the request/response. will attempt to return at least 5MB of data to cache",
                "produces": [
                    "text/text"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Get Request/Response Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request guid",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offset to request from",
                        "name": "from",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/project.PartialRequestResponseData"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/requests/{guid}/payloads": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "sets the payloads associated with a specific request",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Set Request Payloads",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The GUID of the request to update",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "A JSON Object containing the payloads in {'key':'value'} format",
                        "name": "payloads",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/requests/{guid}/search": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Search Request/Response Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request guid",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Base64 encoded bytes to search for",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.RequestSearchResult"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/script_groups": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a list of all script groups",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Get All Script Groups",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.ScriptGroup"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "adds or updates a script group",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Add/Update Script Group",
                "parameters": [
                    {
                        "description": "Script Group details in JSON format",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.ScriptGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/script_groups/{guid}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a specific script group",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Get Script Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Script group guid",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/project.ScriptGroup"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/script_groups/{guid}/archive": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates the archived status of a script group",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Archive Script Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "script group guid",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "archive status to set",
                        "name": "archive",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/script_groups/{guid}/expanded": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates whether a script group is expanded (used for the UI)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Set Script Group Expanded Status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "script group guid",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "expanded state",
                        "name": "expanded",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/script_groups/{guid}/title": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates the title of a script group",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Set Script Group Title",
                "parameters": [
                    {
                        "type": "string",
                        "description": "script group guid",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "title to set",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scripts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a list of all scripts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Get All Scripts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/project.ScriptRun"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scripts/run": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "runs the provided script",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Run provided script",
                "parameters": [
                    {
                        "description": "Run Script Parameters in JSON format",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/scripting.RunScriptParameters"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scripts/{guid}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "gets a single script",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Get A Script",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The GUID of the script to fetch",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scripts/{guid}/append_html_output": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "appends the given HTML to the HTML output of the script",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Append HTML Output for a Script",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The GUID of the script to fetch",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "HTML Output to append",
                        "name": "html",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scripts/{guid}/archive": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates the the archived status of a script",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Archive Script",
                "parameters": [
                    {
                        "type": "string",
                        "description": "script guid",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "archive status to set",
                        "name": "archive",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scripts/{guid}/cancel": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "cancels the provided script",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Cancel the running script",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Script to cancel",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scripts/{guid}/update_progress": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "updates the progress of a currently running script",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scripting"
                ],
                "summary": "Updates running script progress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Script to update",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.ScriptProgressUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "project.DataPacket": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "direction": {
                    "type": "string"
                },
                "displayData": {
                    "type": "string"
                },
                "endOffset": {
                    "type": "integer"
                },
                "guid": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "modified": {
                    "type": "boolean"
                },
                "requestID": {
                    "type": "integer"
                },
                "startOffset": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "project.InjectOperation": {
            "type": "object",
            "properties": {
                "archived": {
                    "type": "boolean"
                },
                "customFilenames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "customPayloads": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "doNotRecord": {
                    "type": "boolean"
                },
                "error": {
                    "type": "string"
                },
                "fuzzDB": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "guid": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "injectDescription": {
                    "type": "string"
                },
                "iterateFrom": {
                    "type": "integer"
                },
                "iterateTo": {
                    "type": "integer"
                },
                "objectType": {
                    "type": "string"
                },
                "percentCompleted": {
                    "description": "Parts of the object which cannot be set by JSON",
                    "type": "integer"
                },
                "request": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/project.InjectOperationRequestPart"
                    }
                },
                "requestsMadeCount": {
                    "type": "integer"
                },
                "ssl": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "totalRequestCount": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "project.InjectOperationRequestPart": {
            "type": "object",
            "properties": {
                "inject": {
                    "type": "boolean"
                },
                "requestPart": {
                    "type": "string"
                }
            }
        },
        "project.InterceptedRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "\u003cbase64 encoded body\u003e"
                },
                "direction": {
                    "type": "string",
                    "example": "Either browser_to_server or server_to_browser"
                },
                "guid": {
                    "type": "string"
                },
                "objectType": {
                    "type": "string"
                },
                "recordAction": {
                    "type": "string",
                    "example": "Either add or delete"
                },
                "request": {
                    "$ref": "#/definitions/project.Request"
                }
            }
        },
        "project.PartialRequestResponseData": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "from": {
                    "type": "integer"
                },
                "to": {
                    "type": "integer"
                }
            }
        },
        "project.Request": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "guid": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "objectType": {
                    "type": "string"
                },
                "payloads": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "requestSize": {
                    "type": "integer"
                },
                "responseContentLength": {
                    "type": "integer"
                },
                "responseContentType": {
                    "type": "string"
                },
                "responseSize": {
                    "type": "integer"
                },
                "responseStatusCode": {
                    "type": "integer"
                },
                "responseTime": {
                    "type": "integer"
                },
                "scanID": {
                    "type": "string"
                },
                "time": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "verb": {
                    "type": "string"
                }
            }
        },
        "project.RequestDifference": {
            "type": "object",
            "properties": {
                "request": {
                    "description": "1 for request number one, 2 for request number two, 0 for both",
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "project.RequestResponseContents": {
            "type": "object",
            "properties": {
                "combinedContentLength": {
                    "type": "integer"
                },
                "dataPackets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/project.DataPacket"
                    }
                },
                "largeResponse": {
                    "type": "boolean"
                },
                "mimeType": {
                    "type": "string"
                },
                "modified": {
                    "type": "boolean"
                },
                "modifiedRequest": {
                    "type": "string"
                },
                "modifiedResponse": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "request": {
                    "type": "string"
                },
                "response": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "project.RequestSearchResult": {
            "type": "object",
            "properties": {
                "endOffset": {
                    "type": "integer"
                },
                "startOffset": {
                    "type": "integer"
                }
            }
        },
        "project.RequestSummary": {
            "type": "object",
            "properties": {
                "guid": {
                    "type": "string"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "hostname": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "requestData": {
                    "type": "string"
                },
                "siteMapPath": {
                    "type": "string"
                },
                "splitRequest": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/project.InjectOperationRequestPart"
                    }
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "project.ScriptGroup": {
            "type": "object",
            "properties": {
                "expanded": {
                    "type": "boolean"
                },
                "guid": {
                    "type": "string"
                },
                "objectType": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "project.ScriptProgressUpdate": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "guid": {
                    "type": "string"
                },
                "objectType": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "project.ScriptRun": {
            "type": "object",
            "properties": {
                "development": {
                    "type": "boolean"
                },
                "doNotRecord": {
                    "type": "boolean"
                },
                "error": {
                    "type": "string"
                },
                "guid": {
                    "type": "string"
                },
                "htmlOutput": {
                    "type": "string"
                },
                "objectType": {
                    "type": "string"
                },
                "percentCompleted": {
                    "type": "integer"
                },
                "requestsMadeCount": {
                    "type": "integer"
                },
                "scriptGroup": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "textOutput": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "totalRequestCount": {
                    "type": "integer"
                }
            }
        },
        "proxy.AddRequestToQueueParameters": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "payloads": {
                    "type": "string"
                },
                "request": {
                    "type": "string",
                    "example": "\u003cbase64 encoded request\u003e"
                },
                "scan_id": {
                    "type": "string"
                },
                "ssl": {
                    "type": "boolean"
                }
            }
        },
        "proxy.InterceptSettings": {
            "type": "object",
            "properties": {
                "browserToServer": {
                    "type": "boolean"
                },
                "serverToBrowser": {
                    "type": "boolean"
                }
            }
        },
        "proxy.InterceptedRequestResponse": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "\u003cbase64 encoded body\u003e"
                },
                "dataPacketGUID": {
                    "type": "string"
                },
                "direction": {
                    "type": "string",
                    "example": "Either browser_to_server or server_to_browser"
                },
                "id": {
                    "type": "integer"
                },
                "requestAction": {
                    "type": "string",
                    "example": "One of: forward, forward_and_intercept_response or drop"
                },
                "requestGUID": {
                    "type": "string"
                }
            }
        },
        "proxy.MakeRequestParameters": {
            "type": "object",
            "properties": {
                "client_cert": {
                    "type": "string"
                },
                "client_cert_key": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "request": {
                    "type": "string",
                    "example": "\u003cbase64 encoded request\u003e"
                },
                "scan_id": {
                    "type": "string"
                },
                "ssl": {
                    "type": "boolean"
                }
            }
        },
        "proxy.PayloadEntry": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "isDirectory": {
                    "type": "boolean"
                },
                "resourcePath": {
                    "type": "string"
                },
                "samplePayloads": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subEntries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/proxy.PayloadEntry"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "proxy.ProxySettings": {
            "type": "object",
            "properties": {
                "http11ProxyAddr": {
                    "type": "string"
                },
                "http11ProxyListening": {
                    "type": "boolean"
                },
                "http11UpstreamProxyAddr": {
                    "type": "string"
                },
                "maxConnectionsPerHost": {
                    "type": "integer"
                },
                "openFile": {
                    "description": "cannot be set externally",
                    "type": "string"
                },
                "openProcessPID": {
                    "description": "cannot be set externally",
                    "type": "integer"
                },
                "openTempFile": {
                    "description": "cannot be set externally",
                    "type": "string"
                }
            }
        },
        "scripting.RunScriptParameters": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/scripting.ScriptCode"
                    }
                },
                "development": {
                    "type": "boolean"
                },
                "scriptGroup": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "scripting.ScriptCode": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "mainScript": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Proximity Core",
	Description: "This provides the common functions which are relied upon by the Proximity frontends.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
